#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.4.0"
URL=http://tpnfc.net/dist/mattermost-team-linux-amd64.tar.gz

dl $URL /usr/local/src
